before_script:
  - python --version
  - pip config set global.index-url https://${ARTIFACTORY_USER}:${ARTIFACTORY_PASS}@${ARTIFACTORY_REGISTRY}/artifactory/api/pypi/pypi-remote/simple
  - pip install -U virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip

stages:
  - sca
  - build
  - test
  - coverage
  - docs
  - pages

sca:
  stage: sca
  image: python:3.12
  needs: []
  script:
    - pip install .[sca]
    - pylint src/mypackage

build:
  stage: build
  image: python:3.12
  needs: [sca]
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/*.whl

test:
  stage: test
  image: python:3.12
  needs: [build]
  script:
    - pip install .[test]
    - pytest

coverage:
  stage: coverage
  image: python:3.12
  needs: [test]
  script:
    - pip install .[test]
    # Output coverage report to an xml file
    #- pytest --cov=src/mypackage --cov-report=xml
    # Output coverage report to the console
    - pytest --cov=src/mypackage
    # upload coverage to codecov only if your repository is public(available on GitHub for example)
    #- codecov  
  #artifacts:
    #reports:
      #cobertura: coverage.xml
    #paths:
      #- coverage.xml

docs:
  stage: docs
  image: python:3.12
  needs: [coverage]
  script:
    - pip install .[doc]
    # Generate documentation from docstrings
    - sphinx-apidoc -o docs/api src/mypackage
    # Build the full HTML documentation
    - cp ./sphinx/index.rst ./docs/
    - sphinx-build --conf-dir sphinx -b html docs docs/_site
  artifacts:
    paths:
      - docs/_site/

pages:
  stage: pages
  when: manual
  before_script: []
  # Make available the docs/_site/ artifact from the docs stage 
  dependencies:
    - docs
  needs: [docs]
  script:
    - mv docs/_site public
  artifacts:
    paths:
      - public
  only:
    - main
