project:
  type: website
  output-dir: docs/_site

website:
  title: "mypackage Documentation"
  search: true
  navbar:
    left:   
      - text: Home
        file: docs/en/index.md
      - text: Installation
        file: docs/en/installation.md
      - text: Usage
        file: docs/en/usage.md
      - text: CI/CD
        file: docs/en/cicd.md
      - text: Generating Documentation
        file: docs/en/doc_generation.md
    right:
      - text: API Reference
        file: docs/reference/index.qmd

format:
  html:
    theme: cosmo

# Include all .md and .qmd files from docs/
files:
  - docs/**/*.md
  - docs/**/*.qmd

# Generate API documentation from Python docstrings
quartodoc:
  dir: docs/reference
  package: mypackage