project:
  type: website
  output-dir: _site

website:
  title: "mypackage Documentation"
  search: true
  navbar:
    left:
      - text: Home
        file: index.md
      - text: Installation
        file: installation.md
      - text: Usage
        file: usage.md
      - text: API Reference
        file: api.md
      - text: Development
        file: development.md
