name: CI

on:
  push:
    branches: [main]
  pull_request:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  sca:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install .[sca]
      - name: Run pylint
        run: pylint src/mypackage

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: sca
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: pip install .[test]
      - name: Run tests
        run: pytest

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: pip install .[test]
      - name: Run coverage
        run: pytest --cov=src/mypackage --cov-report=xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      #- name: Upload to Codecov
      #  uses: codecov/codecov-action@v4
      #  with:
      #    files: coverage.xml

  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v4
      - name: Set up Quarto
        run: pip install .[doc]
      - name: Generate reference qmd files from docstrings
        run: quartodoc build
      - name: Render docs and reference
        run: quarto render      
      - name: Upload docs site
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: _site/

  pages:
    name: Deploy Pages
    runs-on: ubuntu-latest
    needs: docs
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Download docs site
        uses: actions/download-artifact@v4
        with:
          name: docs-site
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy
        uses: actions/deploy-pages@v4
