name: Pages

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:

  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'   
    steps:
      - uses: actions/checkout@v4
      # Generate the documentation using Sphinx
      - name: Set up Sphinx
        run: pip install .[doc]
      - name: Generate documentation from docstrings
        run: sphinx-apidoc -o docs/api src/mypackage
      - name: Build the full HTML documentation
        run: |
          cp ./sphinx/index.rst ./docs/
          sphinx-build --conf-dir sphinx -b html docs docs/_site
      # Generate the documentation using Quarto
      #- name: Set up Quarto
      #  run: pip install .[doc]
      #- name: Generate reference qmd files from docstrings
      #  run: quartodoc build
      #- name: Render docs and reference
      #  run: quarto render  

      - name: Upload docs site
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: docs/_site/

  pages:
    name: Deploy Pages
    runs-on: ubuntu-latest
    needs: docs
    # This job will only run when the workflow is manually triggered and on push to main
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Download docs site into a public folder
        uses: actions/download-artifact@v4
        with:
          name: docs-site
          path: public
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy
        uses: actions/deploy-pages@v4
